# LOCAL (DEV)

spring.datasource.url=jdbc:postgresql://ep-old-boat-aefvmtxv-pooler.c-2.us-east-2.aws.neon.tech/delivery?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=tu_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.application.name=Delivery

server.port=8082

# microservicios en local
client-service.url=http://localhost:8080
edge-service.url=http://localhost:8083
restaurante-service.url=http://localhost:8081

# importante
spring.cloud.config.enabled=false
spring.config.import=optional:configserver:

feign.httpclient.enabled=true