spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8082}

#client-service.url=${CLIENT_URL}
#edge-service.url=${EDGE_URL}
#restaurante-service.url=${RESTAURANTE_URL}