# LOCAL (DEV)

spring.config.import=optional:configserver:
spring.cloud.config.enabled=false

spring.datasource.url=jdbc:postgresql://ep-old-boat-aefvmtxv-pooler.c-2.us-east-2.aws.neon.tech/Cliente?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZsKpSF4J5CVQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8080

delivery-service.url=http://localhost:8082
restaurante-service.url=http://localhost:8081