spring.application.name=Edge

# ========================
# DATABASE (Render / Neon)
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ========================
# SERVER (IMPORTANTE EN RENDER)
# ========================
server.port=${PORT:8083}


# ========================
# MICROSERVICIOS
# ========================
#restaurante-service.url=${RESTAURANTE_SERVICE_URL}
#cliente-service.url=${CLIENTE_SERVICE_URL}
#delivery-service.url=${DELIVERY_SERVICE_URL}
#edge-service.url=${EDGE_SERVICE_URL}
#frontend.url=${FRONTEND_URL}

# ========================
# MAIL
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# SPRING CLOUD
# ========================
eureka.client.enabled=false
spring.cloud.config.enabled=false